### ISSUE TITLE
Pokemon heart gold on black screen

### ISSUE THREAD

**Issue by Lement22** [DS-Homebrew/nds-bootstrap#1210]
**Console Configuration: New Nintendo 3DS with Luma3DS with SD card. Firmwares 11.14.0-46U 
**TWiLight Menu++ Version: V 21.1.1 Bootsatrap Release and nds-bootstrap v 0.44.2
**TWiLight Menu++ Theme: Nintendo 3DS/Dark

### Expected behaviour

Start the clean Pokemon Heart Gold room without AP Patch. Start the save game.

### Actual behaviour

The room starts without problems but once the game is loaded it stays on a black screen, I tried to start a new game, but the problem persists. In older versions of TWiLight Menu ++ I could play it without problems.

### Steps to reproduce

1.Start the Pokemon Heart Gold room
2.Load saved game
3.The console goes black screen

**Comment by Lement22** [comment]
RocketRobz The problem only occurs in the Heart Gold version. The Soul Silver version did work fine in nds-bootstrap 0.44.

**Comment by kaiomatico** [comment]
Just a side info: Heart Gold works fine on Version 0.44.2 on a Nintendo DSI, so maybe this is 3DS specific

**Comment by Ryper-maximoft** [comment]
got the same issue since 0.44.1  i put ann issue report but i think i wrote it wrong, finally someone was heard thank you very much

**Comment by RocketRobz** [comment]
I have a feeling that the both the cloneboot and NO$GBA fixes are what caused the issue.
Can you please update to the latest nds-bootstrap nightly build?

**Comment by Lement22** [comment]
Update to version 0.44.2, in the menu configuration of games and apps in the Bootstrap option change to Nightly (Ver. 24243ff4), but even so the problem persists. Is that version the last one?

**Comment by RocketRobz** [comment]
The latest commit is 1bb1eb6, so your nightly build is out of date.
Another user has already tested it, as is fixed, so I'll close this.

**Comment by Fnaf5000leaked** [comment]
hey no, this is still an issue I am having with the current version of twilight menu. Granted, I'm using a rom hack (refined gold overhaul) with an anti-piracy patch.

**Comment by RocketRobz** [comment]
> hey no, this is still an issue I am having with the current version of twilight menu. Granted, I'm using a rom hack (refined gold overhaul) with an anti-piracy patch.

Loading the save data causes a black screen, or is it a different issue?
If it occurs when loading the save data, try re-launching the game with a DS game cart inserted.

**Comment by Fnaf5000leaked** [comment]
I'm using a flash card for this. Loading the save data causes a black screen. Sometimes I can load the game, in which any fade to black could be permanent.
