### ISSUE TITLE
Newer NSMB Crash W4 Title screen -- Skawo imagines it is that -- im using E rom B4DS

### ISSUE THREAD

**Issue by EpicDoodleboy2** [DS-Homebrew/nds-bootstrap#1487]
NDS bootstrap ver.0.66.0
DS Lite NO EXPANSION PAK
Flashcard (R4 2021)

Newer DS crash
When saving at W4 and going back into the title screen it crashes and I've reported to the Admin of Newer team and it was in fact NDS Bootstrap that is causing the problem and it's not his nor my ds at fault not even the Clone cart that I have Here are the images that show the crash report

![TOP](https://user-images.githubusercontent.com/111697934/201474473-a67fcdda-588c-41dd-844b-c8dc4d290012.jpg)
![BOTTOM](https://user-images.githubusercontent.com/111697934/201474476-150a0c00-8d25-4f33-bfa9-2b2d74e428e4.jpg)

**Comment by EpicDoodleboy2** [comment]
I've fixed it via flashcard firmware

**Comment by RocketRobz** [comment]
Using the flashcard firmware does not fix the issue in nds-bootstrap.

**Comment by EpicDoodleboy2** [comment]
I used The YSmenu firmware which fixed the crash bug and when switching back into NDS Bootstrap It crashes like the pictures that you see if you want video footage, I'll give the footage.

**Comment by RocketRobz** [comment]
> I used The YSmenu firmware which fixed the crash bug and when switching back into NDS Bootstrap It crashes like the pictures that you see if you want video footage, I'll give the footage.

No need.
Using the flashcard firmware works around the issue. It does not fix the issue in B4DS.

**Comment by RocketRobz** [comment]
Also, the reason why the crash occurs is most likely due to the game's heap being shrunk.
Inserting an expansion pak may fix this, as it cuts down shrinking the heap.

**Comment by EpicDoodleboy2** [comment]
hold up, how does the flashcard firmware work around the issue
(Not only that how does NDS Bootstrap work and how does TWL not use the ds's full power as a hardware option for games--this is out of topic)

**Comment by RocketRobz** [comment]
The flashcard firmware/kernel works differently from nds-bootstrap.

nds-bootstrap patches the actual SDK card functions to use custom code. In B4DS mode, we use the flashcard's DLDI driver.
To use the DLDI driver in retail games, we shrink the game's heap so that it doesn't touch the DLDI driver and our custom code (and as a side effect, breaks some games which uses all of the heap).
On DSi/3DS, the heap isn't shrunk due to more memory being available, and is also why *Newer* works on those consoles.

For the flashcard firmware/kernel, the patching works differently, as the SDK functions are not patched, due to flashcards having a feature to basically emulate an original cartridge. Because of that, the game's heap is untouched, and allows *Newer* to work on flashcards just fine.

**Comment by RocketRobz** [comment]
Should hopefully be fixed by 44c5a1aab4453bdf1cf1f207424cf3fd43c3d071

**Comment by EpicDoodleboy2** [comment]
After the update the W4 menu screen works now!
