### ISSUE TITLE
Alice in Wonderland game braking problems.

### ISSUE THREAD

**Issue by Minehors** [DS-Homebrew/nds-bootstrap#1512]
**Your console:** Old 3ds xl on latest firmware (11.16.0-49E)

**Launch Method:** Via the 3ds sd card was installed trough a cia file via fbi

**Version used:** Release v0.68.0

**Game tested/used/applicable:** Alice in Wonderland (Europe) (En,Fr,De,Es,It,Nl) (NDSi Enhanced)

**Save file:** [nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/10417111/nds-bootstrap.zip)

**Expected Behavior:** Saving, no freezing, hitting enemies work and going trough the next level works.

**Actual Behavior:** Saving properly, Freezing when doing so (saving ofc), When entering new level also freezing on loading screen, Enemies not able to defeat.

### Steps to reproduce
1. Just put the legit nds file into your games folder. so twilight and nds bootstrap can read it.
2. open the game
3. trying to do the tutorial and see for your self if you can get to the end if that works proceed to the next level cuz there you learn hit enemies and can save. If you cant hit the enemies / save then you know what problem i have.

### nds-bootstrap.ini

```[NDS-BOOTSTRAP]
NDS_PATH = sd:/nds_roms/4798 - Alice in Wonderland (DSi Enhanced) (E).nds
SAV_PATH = sd:/nds_roms/saves/4798 - Alice in Wonderland (DSi Enhanced) (E).sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
CACHE_FAT_TABLE = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DSI_MODE = 1
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = 1
REGION = 2
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
USE_ROM_REGION = 1
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
SLEEP_MODE = 1
```

 
### Logs
[NDSBTSRP.LOG] https://github.com/DS-Homebrew/nds-bootstrap/files/10417144/NDSBTSRP.LOG

### Will you be available for future issues and/or replies?
yes

**Comment by RocketRobz** [comment]
Sounds more like an AP issue than an nds-bootstrap issue, as the AP-fix was most likely made with DS mode in mind.
Try switching `Run in` to `DS mode` in the per-game settings menu.

**Comment by Minehors** [comment]
> Sounds more like an AP issue than an nds-bootstrap issue, as the AP-fix was most likely made with DS mode in mind. Try switching `Run in` to `DS mode` in the per-game settings menu.

still the same thing even tried to re-upload to the sd card the nds file. with a brend new save with Run in DS mode nothing changes still the same bugs. I experience.

**Comment by RocketRobz** [comment]
The issue persists even with the corrected AP-fix, which means there's possibly an undocumented AP measure implemented.

**Comment by Sukotto-1999** [comment]
I can reproduce it as well except seems to save. when i load the game straight with my R4 flashcart, i can defeat any enemies, plus save correctly, my flashcart does not support DSi Enhanced features, and can't load any DSi exclusive game. Well i don't care about the CycloDS iEVO. Maybe, try using only the cheat version of the AP-patch.

**Comment by Minehors** [comment]
> I can reproduce it as well except seems to save. when i load the game straight with my R4 flashcart, i can defeat any enemies, plus save correctly, my flashcart does not support DSi Enhanced features, and can't load any DSi exclusive game. Well i don't care about the CycloDS iEVO. Maybe, try using only the cheat version of the AP-patch.

I fixed it after i bought an Acekard clone now i can play the game without problems

**Comment by Sukotto-1999** [comment]
Still occuring on version 1.0.0 even with a donor DSi-enhanced cartridge

**Comment by Sukotto-1999** [comment]
Whoops, new fix does not work.

**Comment by RocketRobz** [comment]
> Whoops, new fix does not work. Maybe a update when new Twilight menu releases

afaik, nightly TWLMenu++ builds no longer bundles AP fixes, so yes, wait until the new release.

**Comment by Sukotto-1999** [comment]
i already made a custom AP-database for use with DS-Scene Rom Tool which include patches for Final Fantasy Crystal Chronicles: ROF, and an improved anti-piracy patch for Alice in Wonderland (PAL regions), in which my custom database is coming soon. there will be plans to make changes to my custom AP-database for DS-Scene Rom Tool, including implementing an improved anti-piracy fix for the following games:
Anpanman to Touch de Waku Waku Training
Golden Sun: Dark Dawn (DSProtect 2.01/s patching from NDS-bootstrap to offsets)
Pokemon Black/White and Pokemon Black/White 2 (for DSi mode compatibility) (only with clean dumps)
Dragon Quest V (JPN)

**Comment by Sukotto-1999** [comment]
UPDATE: My custom database for DS-Scene Rom Tool has been released, just replace the offsets.dsapdb file in the database folder in the data folder with the custom one. Have fun!

[offsets.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12765642/offsets.zip)


Notes: I'll be releasing the tools to encrypt and decrypt the tools from pleonex (credit to him).

**Comment by Dartz150** [comment]
> UPDATE: My custom database for DS-Scene Rom Tool has been released, just replace the offsets.dsapdb file in the database folder in the data folder with the custom one included in zip file. Have fun!
> 
> [offsets.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12765642/offsets.zip)
> 
> Notes: I'll be releasing the tools to encrypt and decrypt files from DS-Scene Rom Tool from pleonex (credit to him).

I'll be testing those patches with pre-1.0.0 releases to check how they are working. 

BTW, do you know by any chance if this could be also a bad patch that needs review?
#271

**Comment by Sukotto-1999** [comment]
> > UPDATE: My custom database for DS-Scene Rom Tool has been released, just replace the offsets.dsapdb file in the database folder in the data folder with the custom one included in zip file. Have fun!
> > [offsets.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12765642/offsets.zip)
> > Notes: I'll be releasing the tools to encrypt and decrypt files from DS-Scene Rom Tool from pleonex (credit to him).
> 
> I'll be testing those patches with pre-1.0.0 releases to check how they are working.
> 
> BTW, do you know by any chance if #271 could be also a bad patch that needs review?

Specifically, this method only worked on flashcarts btw. It maybe a bad patch. Maybe, some hacker could patch the DSProtect code in SAGA 3 for it to work on nds-bootstrap. Huh?

**Comment by Sukotto-1999** [comment]
EDIT: The prototype for All Kamen Rider: Rider Generation (which was found by Forest of Illusion) is confirmed to have the DSProtect code as in the retail game. Maybe someone could patch the prototype to get it working.

**Comment by Sukotto-1999** [comment]
Hello. I was able to gain some information on the DSProtect anti-piracy protection. DSProtect is an anti-piracy library/system developed by NetAgent in association with Nintendo.

It turns out that the previous patch patches out the ROM read test, but not the system info test, that is the absolute reason why the previous patch still triggers that unique protection. First this game runs the DSProtect checks, ROM read test and system info test. If any of the DSProtect checks fail, in this game's case, all enemies will be invincible, preventing further progress. Now this current patch improves on patching the protection, which also patches the system info test. So now, nds-bootstrap cannot evade the system info test. DSProtect's system info test is failed under two conditions: MAC address is either 00:00:00:00:00:00 or 00:09:BF:00:00:31. I did some research using the DeSmuME emulator.

More info can be found here:
https://tcrf.net/The_Cutting_Room_Floor:Common_Things/DS_Protect_Explanation
