### ISSUE TITLE
Animal Crossing Wild World DS to DS connection crashing

### ISSUE THREAD

**Issue by tempaccountforacww** [DS-Homebrew/nds-bootstrap#1592]
Can't reopen this issue, that's why I'm opening a duplicate issue, sorry I'm new here https://github.com/DS-Homebrew/nds-bootstrap/issues/985

**Your console:**
_2x Nintendo DSi XL_

**Launch Method:**
_TWiLight Menu++ v13.1.0
Because this comment https://github.com/DS-Homebrew/nds-bootstrap/issues/985#issuecomment-665012335 meant that the version was stable.
So I found this version of nds-bootstrap [here](https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v13.1.0)._

_TWiLight Menu++ v25.3.0
Because https://github.com/DS-Homebrew/nds-bootstrap/issues/985#issuecomment-1241014210 said, that version 0.64 would work. so I searched for the 0.64 Version and found it [here](https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.64.0), where it was told that it is in the v25.3.0 of the twi menu_

- _Switching between the above mentions TWiLight Menu++ versions (means copying BOOT.NDS + nds to the root if the SD-Cards)_
- _using a different (used, not new) freshly formatted micro SD-Card_
  - _all together I used the following:_
    - _4GB Platinum (Secure Digital Card)_
    - _8GB microSDHC Class 6 + SanDisk microSD/HC/XC Adapter_
    - _8GB SanDisk microSDHC Class 4 + hama microSD/HC/XC Adapter_

_TWiLight Menu++ v25.11.0
of corse the newest version, because I thought it would ne fixed meanwhile_

**Version used:**
_standard_

**Game tested/used/applicable:**
_Animal Crossing - Wild World (Europe) (En,Fr,De,Es,It).nds_
_MD5: 9d0dda4ca7227c31bb31002342b8530e_
_SHA1: 858da57a18852e75304e423519dde6a548d5264b_

**Save file:**
[Animal Crossing - Wild World (Europe) (En,Fr,De,Es,It).sav.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12044326/Animal.Crossing.-.Wild.World.Europe.En.Fr.De.Es.It.sav.zip)

**Expected Behavior:**
_It was expected to not disconnect from the local connection._

**Actual Behavior:**
_exactly the same as here_ https://github.com/DS-Homebrew/nds-bootstrap/issues/985#issue-664646685

### Steps to reproduce
_exactly the same as here_ https://github.com/DS-Homebrew/nds-bootstrap/issues/985#issue-664646685

_I'd like to add, that sometimes it takes a few seconds until the connection crash, sometimes 1 - 2 Minutes.
I think it matters, how much both players are doing simultaneously, but that's just a guess_

### nds-bootstrap.ini
```[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = sd:/Nintendo DS/Animal Crossing - Wild World (Europe) (En,Fr,De,Es,It).nds
SAV_PATH = sd:/Nintendo DS/saves/Animal Crossing - Wild World (Europe) (En,Fr,De,Es,It).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = de
LANGUAGE = -1
REGION = 2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Logs
_There is no "LOGGING" text in the nds-bootstrap.ini file_

#### What I've tried so far
- _Changing CPU speed to 67mhz_
- _Deactivating Card-Read-DMA (because https://github.com/DS-Homebrew/nds-bootstrap/issues/985#issuecomment-885993773 said it could fix it)_

#### What I have found so far
- _With TWiLight Menu++ v25.3.0 we could play the "longest" (~5 minutes). but mostly, if both players were afk._
- _as soon as both players starts playing actively and/or one of the both players is moving its position (in real life, in the room) ... the problems start, which somehow briefly made me think of a loose connection with the SD card or the wireless connection module_
- _I've noticed that mario kart ds for example is crashing almost everytime before a race can start (1x TWiLight Menu++ game + 1x Unlauncher --> DS Download). on the other hand mario party ds works everytime 100% guaranteed- idk why (1x TWiLight Menu++ game + 1x Unlauncher --> DS Download)._

### Will you be available for future issues and/or replies?
_Yes_

**Comment by RocketRobz** [comment]
Is it fixed in nds-bootstrap v1.0.0?

**Comment by stosumarte** [comment]
> Is it fixed in nds-bootstrap v1.0.0?

I’m having the same problem with nds-bootstrap v1.0.0

connecting tw dsi to a ds lite with a legit gamecard.

didn’t work on earlier versions either.

**Comment by gaker19sc** [comment]
The issue persists, I am able to get into a game sometimes, but it will crash.

**Comment by RocketRobz** [comment]
Since the release of v1.6.0, has this issue been fixed?

**Comment by kEnder242** [comment]
Sadly no.  v1.6.2 crashed.  Tried DSi->DS and DS->DSi hosting connections.

![acww_ndsbs_162](https://github.com/user-attachments/assets/93a6b5fd-6322-4e1d-9d68-7ad0f2210f15)

Per my previous notes, I think the last time I was able to connect was April 2020.  Looking for the word 'wifi' during that time shows this change, no idea if it is related.  https://github.com/DS-Homebrew/nds-bootstrap/commit/48b785dd73c8a256f5d776c1f8420b6a4d055b74

**Comment by RocketRobz** [comment]
> Sadly no. ACWW crashed with v1.6.2. Tried DSi->DS and DS->DSi hosting connections.

Are you sure? Please open the in-game menu (by pressing L+Down+Select) after launching the game, and see if the correct version is displayed on the bottom screen.

> Per my previous notes, I think the last time I was able to connect was April 2020. Looking for the word 'wifi' during that time shows this change, no idea if it is related. https://github.com/DS-Homebrew/nds-bootstrap/commit/48b785dd73c8a256f5d776c1f8420b6a4d055b74

It is not related.

**Comment by kEnder242** [comment]
![PXL_20240904_043224466](https://github.com/user-attachments/assets/1d73b6ac-05df-4100-8dac-94f00cb83bbe)

**Comment by RocketRobz** [comment]
Have you tried turning off the `Card Read DMA` setting in the per-game settings menu (opened in TWLMenu++ by pressing `Y` button)?

**Comment by kEnder242** [comment]
I noticed DMA was enabled on one but off on the other.  Immediate crash with both enabled via the Y menu.  Turning it off allowed me to join and play for a few seconds.  

![PXL_20240904_045039702](https://github.com/user-attachments/assets/d0fdfe6c-b7b6-42fd-8c6f-6cd312c21809)
![PXL_20240904_045143593](https://github.com/user-attachments/assets/9f43776a-e35b-4d48-99fa-2fedf1da05ea)

**Comment by gwyn-b** [comment]
Just commenting to say that my partner and I are  both having the same issue; we're both on v1.6.2, playing on new 3ds xl. Have not tried without Card Read DMA yet, but we're gonna give that a go and report back.

**Comment by RocketRobz** [comment]
> Just commenting to say that my partner and I are both having the same issue; we're both on v1.6.2, playing on new 3ds xl. Have not tried without Card Read DMA yet, but we're gonna give that a go and report back.

Please update nds-bootstrap before testing.

**Comment by Citrodata** [comment]
After dumping my own copy, checking that it matches with the hash shown at the top.
Updating to Version 2.4.6, I could test if it works.
I sadly only would have a New 2DS XL and a New 3DS if that's okay I would test it.

**Comment by Skote2** [comment]
Wild world ds to ds communication is crashing on mine with the latest nds bootstrap and twilight menu. I am using a modded 3ds with the nds bootstrapped version and ds lite with a genuine cartridge.
TWiLight Menu++ v27.13.3
nds-bootstrap v2.4.6

Is there a log collection guide somewhere?

**Comment by RocketRobz** [comment]
> Hi [@RocketRobz](https://github.com/RocketRobz), my partner and I managed to reproduce this with two JP DSis and the latest release of nds-bootstrap (2.9.1). TWLMenu++ is also at the latest version. Card DMA is off for the game (the issue happens with both DMA on and off).
> 
> Can we provide any further / better logs to help with debugging this issue?

The only log made is the one before the game boots (`NDSBTSRP.LOG`), so unfortunately, it wouldn't be helpful.
