### ISSUE TITLE
Inazuma Eleven Error: Undefined Instruction!

### ISSUE THREAD

**Issue by Youngei402tw** [DS-Homebrew/nds-bootstrap#1646]
### Game Console(s) used

- [ ] Nintendo DS
- [X] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Flashcart

### Version used

v1.0.1 release

### Game tested/used/applicable

Inazuma Eleven (Europe)

### Expected Behavior

when pressing X, it will bring up the menu, and I can choose any tab in the menu without any issue.

### Actual Behavior

when pressing X, it will bring up the menu, but every tab will the to Error: Undefined Instruction!

### Steps to reproduce

1. launch Inazuma Eleven (Europe).
2. press X to bring up the in-game menu.
3. choose any tab in the menu will lead to Error: Undefined Instruction!

### nds-bootstrap.ini

`
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = fat:/roms/nds/Inazuma Eleven (Europe).nds
SAV_PATH = fat:/roms/nds/saves/Inazuma Eleven (Europe).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = 1
DSI_MODE = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH = fat:/_nds/nds-bootstrap/apFixCheat.bin
`

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/13186037/NDSBTSRP.LOG)

### Other notes

I tried using my flashcard kernel to launch, and it does launch with no issue.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Try downgrading TWiLight Menu++ to v26.1.0.

**Comment by Youngei402tw** [comment]
update: the issue is solved when using TWiLight Menu++ to v26.1.0, meaning there is a issue in the newer release?

**Comment by RocketRobz** [comment]
> update: the issue is solved when using TWiLight Menu++ to v26.1.0, meaning there is a issue in the newer release?

The newer release was intended to fix the AP issues that somehow we're still occurring, but apparently, it made things worse.

**Comment by Youngei402tw** [comment]
roger that! look forward for further development! great work btw, made my dslite come back to life.

**Comment by Youngei402tw** [comment]
Well, I just wanna update on this. When I lost a match in the game, the game will froze with a white screen... Not sure if this is related though

**Comment by RocketRobz** [comment]
> Well, I just wanna update on this. When I lost a match in the game, the game will froze with a white screen... Not sure if this is related though

That's probably one of the AP issues then. It hopefully will be fixed in the next version.
