### ISSUE TITLE
Hotel Dusk: room 215 - graphical issues

### ISSUE THREAD

**Issue by hubert-skowronek** [DS-Homebrew/nds-bootstrap#231]
Hotel Dusk: room 215 has glitched opening - there are green, flickering bars near screens' borders

nds-bootstrap 9.2.0

Update: nds-bootstrap 0.50.0:

- [x] flickering green/black bars
- [ ] screen switch flickering in TWL clock speed
- [ ] static green/black lines in inventory menu

**Comment by hubert-skowronek** [comment]
@RocketRobz As of 0.14.0 RC1 problem seems to be gone! Do you know by any chance what was the reason of those green, flickering bars?

**Comment by RocketRobz** [comment]
I guess it's due to the data load size being 128KB, which may cause a slight delay.

**Comment by hubert-skowronek** [comment]
@RocketRobz do you think that this issue can be closed now and this change will be persistent?

**Comment by FlameAlt53** [comment]
the `non_blocking_io` branch has been merged to master, should this be closed?

**Comment by hubert-skowronek** [comment]
Unfortunately green flickering bars persist during the opening animation, they are just rarer than before. The issue should be reopened. Tested on nds-bootstrap 0.17.0

**Comment by RocketRobz** [comment]
I'm guessing this is related to card read DMA.

**Comment by ahezard** [comment]
This game uses dma indeed so it could be linked to #517

**Comment by ahezard** [comment]
there is no sleep method so the current dma implementation is not compatible

**Comment by ahezard** [comment]
the cecached option should help

**Comment by hubert-skowronek** [comment]
@ahezard the issue still occurs for the latest nightly b9e26ac

**Comment by ahezard** [comment]
Please test with latest nightly and report if the issue is reduced now that #517 have been implemented

**Comment by hubert-skowronek** [comment]
After Hyde shoots Bradley in the intro the green flickering appears - so the issue still occurs

**Comment by ahezard** [comment]
that was fast, thanks!

**Comment by hubert-skowronek** [comment]
@ahezard no problem :-) I observe your work on daily basis, following every change ;)

**Comment by hubert-skowronek** [comment]
@NightYoshi370 do you mean flickering (twitching of top and bottom screens) or flickering green bars during cutscenes?

**Comment by Adubbz** [comment]
As of the latest release (0.29.2), NTR mode does fix the flickering screen swapping. However, the green bars continue to appear on the side of the screen intermittently both in a number of cutscenes and whilst moving around.

**Comment by kaosjr** [comment]
As of latest release (0.35.1) the green flickering bars seem to be much rarer, though I did notice them a few times while playing the game still in NTR mode. Did not see them in the opening however.

**Comment by luigiandmariooooooo** [comment]
personally, I still have the green bars in the opening but did not notice them during gameplay

my setup - new 2ds xl; twilight menu v15.1.1; nds bootstrap v0.35.1; luna v10.2

**Comment by RocketRobz** [comment]
Can anyone test if this happens on the latest nightly?

**Comment by hansoljin** [comment]
On 0.37.0 release. DSi XL, Unlaunch 1.9.

133mhz glitches the displays. Each screen keeps flickering the other's image. Does not happen in 67mhz.

I don't notice this "green flickering" though. Just the two screens flickering back and forth in TWL speed.

**Comment by RocketRobz** [comment]
I think it's safe to assume this is fixed then.

**Comment by hansoljin** [comment]
Inka (from DSi Mode Hacking Discord) and I have consistently reproduced the green/black bars on the latest nightly.

To reproduce, you must run the game from the console SD (not the flashcard SD via SCFG), and VRAM Boost must be off. So it is tied to a lack of VRAM??

This issue should be reopened.

**Comment by lifehackerhansol** [comment]
Got around to testing this again. Screen switching still happens in TWL clock speed, so perhaps this should be added to the blacklist.

I'm not seeing the green flickering though, both VRAM mode DS and DSi. Can someone else confirm this?

**Comment by lifehackerhansol** [comment]
It seems the flickering in the opening has been completely eliminated; there is still a graphical bug where a static black/green row of lines are present in the inventory.

**Comment by RocketRobz** [comment]
Haven't noticed any green/black lines on my side, as of the latest release (or the latest nightly).
