### ISSUE TITLE
Moonshell DPG playback

### ISSUE THREAD

**Issue by shutterbug2000** [DS-Homebrew/nds-bootstrap#55]
As it stands, moonshell will play back DPG files for a few seconds, then crash.

**Comment by Robz8** [comment]
Was this tested in the latest bootstrap version?

**Comment by shutterbug2000** [comment]
Yes, I tested a few days ago.

**Comment by NightYoshi370** [comment]
@RocketRobz isn't this issue fixed in the latest build of nds-bootstrap?

**Comment by RocketRobz** [comment]
Not really. Moonshell v1.x crashes on `generating random seed`, due to enabling/disabling extended memory, which is done to prevent the homebrew from overwriting the loaded RAM disk.
It is unknown if Moonshell v2.x has the same issue as well.

**Comment by RocketRobz** [comment]
Progress has been made as of ad180ab9
- Moonshell v1.71 plays videos properly. Tested with video bitrate 192, as higher can cause crash with lots happening on-screen. May still crash randomly, so lowering the video bitrate slightly should reduce chances.
- Moonshell v2 Beta 8.1 crashes after around 5 seconds of video.

**Comment by RocketRobz** [comment]
As of bc7f3c1d, v2.10 now boots properly (with `logbuf.txt` not in the `moonshl2` folder), and the same video tested with v1.71 does not crash.
After that, I re-encoded the video with the highest settings available in DPG4X, and that also did not crash.
