### ISSUE TITLE
Real-Time Clock (RTC) doesn't work correctly on the DSi for some games

### ISSUE THREAD

**Issue by SleepyLark** [DS-Homebrew/nds-bootstrap#827]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.9 + whatever is the latest HiyaCFW ]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.27.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Love Plus [English Translation]
Animal Crossing: Wild World (#700)

### Expected behaviour

The RTC in the game should function the same as the system's clock.

### Actual behaviour

The clock in the game keeps skipping or doesn't work correctly.  For Love Plus, it keeps thinking it's been over 48 hours and keeps prompting the user to save.  It get's worse once Real Time Mode is unlocked as the day keeps resetting despite the day and time still being the same as the system's.  

### Steps to reproduce

1. Launch Love Plus on the DSi (it doesn't matter if it's the Fan-translation or not)
2. Select a save file and press "Real Time Mode"  (I can upload a completed save file later on if needed)
3. Wait a little bit.  The screen should flash and a prompt window will appear saying that the week has changed even though the day is the same.

### Other notes
This issue has been known for a while, however I discovered that when playing it on the 3DS there was no problems with the clock, so it's only affecting the DSi.
I've already tried setting the clock speed to NTR which didn't do anything.

**Comment by SleepyLark** [comment]
I think you may be right.  I have them Wild World opened side-by-side at the moment.  On the DSi the bell chimes about every 5 minutes and flickers to night before saying "Good morning", while on the 3DS the only time it chimed was when it was the top of the hour in-game.  The clock still says the right time and the time of day doesn't appear to change.  Now I'm curious to know what other games have this problem.

**Comment by Ihamfp** [comment]
I sometimes get an RTC bug on Pokemon Platinum as well, the clock/watch thing randomly displays the wrong time for about a second. It's very rare tho, only happened once or twice in 3 hours.
It runs on a DSi with Unlaunch+twlmenu, hiya is installed but not launched.
Might be related to the frequency of game time update, or maybe the RTC randomly fails to answer in time, and it gets more visible the more frequently the game needs it.

**Comment by dasBroetschen** [comment]
Same RTC problem here in "Animal Crossing Wild World" (European)
>> DSi with latest Unlaunch, TwilighMenu++ and NDS-Bootstrap, running from SD-card <<
The game will ring the bell every 5 minutes, the screen flickers and it says "good morning".

RTC seems to not work well in the current state, or am I missing a (ini-file) setting?

**Comment by RocketRobz** [comment]
A .ini file setting will not fix this.

**Comment by dasBroetschen** [comment]
> 
> 
> A .ini file setting will not fix this.

So is there no actual fix for this problem? Or will the it be fixed in future updates?

**Comment by SugaryHull** [comment]
Loading an NDS Bootstrap generated save file to the retail cart for Animal Crossing: Wild World doesn't remedy the issues described above, indicating that the issue persists across saves

**Comment by omarelhajj97** [comment]
> Loading an NDS Bootstrap generated save file to the retail card for Animal Crossing: Wild World doesn't remedy the issues described above, indicating that the issue persists across saves. The card was loaded directly from Unlaunch, ~indicating that HiyaCFW is not related~
> 
> Update: Wiping the save and creating a new one on the retail card did not resolve the issue. The card was launched from Unlaunch. Perhaps it's an issue with EmuNAND

I don't have the knowledge to understand exactly why the problem occurs, but this sounded very strange to me so I decided to try to load my nds-bootstrap generated save file to a R4i with the same backup rom, and that did in fact solve the real-time clock issue. So I don't think that the issue lies that low.

DSi, slot-1 launched from within TwilightMenu++, EUR rom.

**Comment by RocketRobz** [comment]
Why the bug happens, is because arm7 does the loading, instead of arm9.
arm7 handles RTC, so reading from the SD card causes issues with RTC.
One way to fix it, is to optimize the read code somehow, or just by moving the FAT code to arm9, and just have arm7 do the sector reading, so not much time is taken on the arm7 side.

**Comment by RocketRobz** [comment]
Tried ACWW in the `fatOnArm9` branch, and the RTC bug is fixed, it seems!
Can anyone else try this build, and see if the bug is fixed for you as well?
[nds-bootstrap-nightly.zip](https://github.com/ahezard/nds-bootstrap/files/4542070/nds-bootstrap-nightly.zip)
Note that loading takes a while. :P

**Comment by SleepyLark** [comment]
> Tried ACWW in the `fatOnArm9` branch, and the RTC bug is fixed, it seems!
> Can anyone else try this build, and see if the bug is fixed for you as well?
> [nds-bootstrap-nightly.zip](https://github.com/ahezard/nds-bootstrap/files/4542070/nds-bootstrap-nightly.zip)
> Note that loading takes a while. :P
> If the game doesn't boot, try turning off heap shrink.
> 
> EDIT: nvm. After moving around for a while, Day briefly changes to Night, and the bell still chimes.

Tried it on Love Plus with heap shrink off, it couldn't go past the logo screen, same thing with Wild World, unless I'm doing something wrong

**Comment by RocketRobz** [comment]
Set ROM read LED to Power, so that you'll know data is loading.

**Comment by KmvaMaeru** [comment]
I have ACWW in a **3ds** and a _dsi_ and so far the **3ds** version runs normally, the _dsi_ one is the only with that bug and I've already tried with different roms and regions but none of that seems to fix it on the _dsi_.
Actually, Ds to Ds connections seems to fail using the _dsi_ as host and work perfectly with the **3ds** as host because of the bug.
I'm able to experiment and give you info if you need it, but is there a way I can help out in this matter?
I'd love if this was fixed.

**Comment by RocketRobz** [comment]
It seems commit 157eac13 has fixed this.
I need someone else to test this (or the latest) nightly build, before this can be closed.

**Comment by KmvaMaeru** [comment]
Nope, the Dsi at least is not fixed to me :/ (I compiled the last git version and put it as the nightly)

**Comment by omarelhajj97** [comment]
Looks like I am not able to build nds-bootstrap from Linux because of [lzss](https://www.romhacking.net/utilities/826/) being Windows-only, and the [TWiLightMenu-update](https://github.com/RocketRobz/TWiLightMenu-update) repo hasn't been updated in a while. Could someone please share the latest binaries to test?

**Comment by KmvaMaeru** [comment]
@omarelhajj97 I just copy pasted both lzss files on the directory and it worked on windows, it doesn't work on Linux that way?

**Comment by omarelhajj97** [comment]
> @omarelhajj97 I just copy pasted both lzss files on the directory and it worked on windows, it doesn't work on Linux that way?

No, the build fails mid-way because it doesn't find the program in the directory. The files are just a .c source file and a .exe Windows binary.

**Comment by Bihlasagna69** [comment]
> It seems commit [157eac1](https://github.com/ahezard/nds-bootstrap/commit/157eac13a5411b62798e75475e2588da629d5142) has fixed this.
> I need someone else to test this (or the latest) nightly build, before this can be closed.

It worked for me......
....For now, I guess

**Comment by Bihlasagna69** [comment]
> It seems commit [157eac1](https://github.com/ahezard/nds-bootstrap/commit/157eac13a5411b62798e75475e2588da629d5142) has fixed this.
> I need someone else to test this (or the latest) nightly build, before this can be closed.

Actually it didn't work
Today's is ladiday on animal crossing and it keeps saying "ladiday has ended" and 1 second later says "today's ladiday!"

**Comment by paranoid64** [comment]
I have installed the latest version, but the problem still exists. Does anyone have a solution for this ?

**Comment by RocketRobz** [comment]
It would already be in nds-bootstrap, if there is.

**Comment by AbnormalPoof** [comment]
Should we unpin this?

**Comment by RocketRobz** [comment]
Done.
