### ISSUE TITLE
New Super Mario Advance Missing Sound

### ISSUE THREAD

**Issue by Kaisaan** [DS-Homebrew/nds-bootstrap#922]
**Your console:** New 2DS XL
**Launch Method:** Luma3DS 10.1.2 and TWiLightMenu++ 14.2.0
**Version used:** 0.34.0
**Game tested/used/applicable:** [New Super Mario Advance + Take 2](http://kuribo64.net/get.php?id=uD1s0v9bBAGoicx3) ROM hack of New Super Mario Bros. (USA)

**Expected Behavior:** Title screen music should play, new file should load
**Actual Behavior:** Title screen has no music playing, selecting a new file causes a black screen and crashes

### Steps to reproduce
Launch the game on a New3DS system and select a new file. (not sure if issue occurs on O3DS systems as well)

### Other notes
This issue only occurs on my N2DSXL, the game works fine on my DSi XL (unlaunch 2.0, hiyaCFW 1.3.3, TWiLightMenu++ 14.2.0, nds-bootstrap 0.34.0)
There are multiple version of the ROM hack included with the download, each have a different playable character. I have tested the Mario and Luigi patches.

**Comment by RocketRobz** [comment]
Hmm, the ROM size is incorrect in the header.
The size in the header is 0x151CD88. The correct size is 0x1A08868.

**Comment by Kaisaan** [comment]
Another ROM hack that has a different header size is Mario's Holiday, which is also known to be broken on nds-bootstrap (#402). The only difference is that the hack crashes only on DSi systems instead of only on (N)3DS systems.

**Comment by Kaisaan** [comment]
Testing this issue still occurs. Using my N3DS XL on Luma3DS 10.2.1 with TWiLight Menu++ version 24.1.0, and nds-bootstrap 0.54.1. Unable to test right now if this issue doesn't happen on DSi systems still.

**Comment by RocketRobz** [comment]
Commit e904d031 may partially fix the issue, since the full ROM still won't be loaded into RAM.

**Comment by Kaisaan** [comment]
Yeah, the issue is fixed. But now it seems that certain sound effects (jumping, groundpounding, getting a powerup) do not play.

**Comment by spellboundtriangle** [comment]
> Yeah, the issue is fixed. But now it seems that certain sound effects (jumping, groundpounding, getting a powerup) do not play.

On (N)3DS specifically? Seems to be fine on my DSi.

**Comment by spellboundtriangle** [comment]
I can confirm that it still occurs on N3DS on v0.68.0, but it can be worked around by running the game in DSi mode.

**Comment by RocketRobz** [comment]
If the bug still occurs, then the ROM needs to be opened and saved using TinkeDSi, or repacked using DSLazy.
